sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t hicbrowser .
  - docker run -d -p 80:80 hicbrowser
  - docker run -d -e PROXY_PREFIX=/hicbrowser -p 81:80 hicbrowser
  - docker ps -a
  - sleep 20

script:
  - curl -v --fail http://localhost
  - curl -v --fail http://localhost:81/hicbrowser/
  - curl -v --fail http://localhost/fail
